version: "3"
services:
  engecopi:
    image: tomcat:8
    container_name: eng_ter_fornecedor
    ports:
      - "8031:8080"
    environment:
      TZ: "America/Fortaleza"
      EBEAN_PROPS: /etc/ebean.properties
    volumes:
      - ./build/libs/producao-1.0.war:/usr/local/tomcat/webapps/termo.war
      - ./ebean.properties:/etc/ebean.properties
    restart: always
    networks:
      rede_ter_fornecedor:
        ipv4_address: 172.131.1.1
networks:
  rede_ter_fornecedor:
    ipam:
      driver: default
      config:
        - subnet: 172.131.0.0/16
